# Site settings
title: d00x
email: dan@axelby.com
description: "A cross-language cross-target software platform"
baseurl: "http://www.d00x.com/"
url: "http://www.d00x.com/"
twitter_username: axelby
github_username:  thasmin

# Build settings
markdown: kramdown
permalink: pretty
